"use strict";

require("core-js/modules/es.object.define-property.js");

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;

var recepcion = function recepcion() {
  document.getElementById("tagName").textContent = "Recepcion";
  var root = document.getElementById("root");
  root.innerHTML = "\n    <div class=\"animatedItem1\">\n    <h1>Recepcion</h1>\n\n    <div class=\"card\">\n    <article>\n        <h2>Recepcion critica</h2>\n        <p>Las primeras seis temporadas y las temporadas novena y d\xE9cima de The Walking Dead han sido bien rese\xF1adas\n            por cr\xEDticos reconocidos, mientras que las temporadas s\xE9ptima y octava recibieron m\xE1s cr\xEDticas mixtas.\n            En Rotten Tomatoes, la serie tiene una calificaci\xF3n promedio del 81%.</p>\n    </article>\n\n    <article>\n        <h2>Comentarios sobre la diversidad</h2>\n        <p>Algunos cr\xEDticos han comentado sobre la creciente diversidad de la serie. Este enfoque fue inicialmente\n            aplaudido por los comentaristas, pero algunos m\xE1s tarde afirmaron que hab\xEDa alcanzado lo que\n            describieron como \xABmasa cr\xEDtica\xBB. A partir de 2015, algunos comenzaron a preguntarse si el programa\n            estaba en peligro de volverse \xABdemasiado diverso\xBB.\u200B Robert Kirkman ha discutido la creciente\n            diversidad del programa y los c\xF3mics. Describi\xF3 c\xF3mo lamenta la falta de diversidad en los primeros\n            n\xFAmeros de la serie de c\xF3mics y explic\xF3 c\xF3mo habr\xEDan sido \xABmucho m\xE1s diversos\xBB si los hubiera comenzado\n            ahora.</p>\n    </article>\n\n    <article>\n        <h2>Audiencias</h2>\n        <p>Durante su primera temporada, The Walking Dead atrajo entre cuatro y seis millones de espectadores.\n            La audiencia comenz\xF3 a aumentar en su segunda temporada. Durante las temporadas tres a seis, atrajo de\n            diez a diecisiete millones de espectadores.\u200B En 2012, durante su tercera temporada, se convirti\xF3 en\n            la primera serie de cable en la historia de la televisi\xF3n en tener la mayor audiencia total de todas las\n            series entre adultos de 18 a 49 a\xF1os. En 2014, la audiencia total para el estreno de la quinta\n            temporada del programa fue de 17,30 millones, lo que lo convierte en el episodio de una serie m\xE1s visto\n            en la historia del cable.\u200B En 2016, un estudio del New York Times de las 50 series de televisi\xF3n\n            con m\xE1s me gusta en Facebook descubri\xF3 que, como la mayor\xEDa de las otras series de zombis, The Walking\n            Dead \xABes m\xE1s popular en las zonas rurales, particularmente en el sur de Texas y el este de\n            Kentucky\xBB.\u200B Las audiencias comenzaron a disminuir durante la s\xE9ptima temporada y han seguido bajando\n            constantemente, lo que se atribuy\xF3 a una variedad de factores, incluida la presunta muerte de Rick. Al\n            final de la temporada nueve, hab\xEDa menos espectadores que en cualquier otro momento desde la primera\n            temporada del programa.</p>\n    </article>\n    </div>\n    </div>\n    ";
};

var _default = recepcion;
exports["default"] = _default;